<?php

/**
 * QuestionCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    phptest
 * @subpackage model
 * @author     Pascal Larocque
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class QuestionCategory extends BaseQuestionCategory
{

}